### ISSUE TITLE
RPC logging improvements.

### ISSUE THREAD

**Issue by jmalloc** [IcecaveStudios/overpass#19]
Currently we log RPC requests at level `DEBUG` with full request/response objects.

We need logging at level `INFO` that shows the calls being made and the types of arguments and responses, without showing their values (and also #18)

The full request/response objects can still be logged at `DEBUG` level.

**Comment by jmalloc** [comment]
@captainclam PHP version of what we discussed for overpass-js

**Comment by vaidas-lungis** [comment]
Do you use Monolog logger?
How to override bracket placeholders into variables?

**Comment by jmalloc** [comment]
Overpass does not specifically use Monolog, but any PSR-3 compatible logger.

To use PSR style placeholders with Monolog you need to add the [`PsrLogMessageProcessor`](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Processor/PsrLogMessageProcessor.php) to the logger. See [using processors](https://github.com/Seldaek/monolog/blob/master/doc/01-usage.md#using-processors).

**Comment by vaidas-lungis** [comment]
@jmalloc oh nice, didn't see that. thanks!
